bikecoders/ngx-deploy-npm

.editorconfig, .gitignore, .prettierrc, LICENSE, README.md, src/__mocks__/utils/dev-kit-logger.ts, src/collection.json, src/deploy/actions.spec.ts, src/deploy/actions.ts, src/deploy/builder.ts, src/deploy/schema.json, src/engine/defaults.ts, src/engine/engine.spec.ts, src/engine/engine.ts, src/engine/utils/__mocks__/exec-async.ts, src/engine/utils/exec-async.ts, src/ng-add.spec.ts, src/ng-add.ts, src/package-lock.json, src/package.json, src/tsconfig.json
Create the first version of the npm deployer
=> Create npm deployer

src/.versionrc.json, src/CHANGELOG.md, src/package-lock.json, src/package.json
None
Issue Number: #6 
The changelog is generated automatically from git metadata.
`standard-version` does the following:
1. bumps the version in metadata files (package.json, composer.json, etc).
2. uses [conventional-changelog](https://github.com/conventional-changelog/conventional-changelog) to update _CHANGELOG.md_
3. commits _package.json (et al.)_ and _CHANGELOG.md_
4. tags a new release
closes #6
=> feat: add standard-version

src/ng-add.spec.ts, src/ng-add.ts
The test of the ng-add feature are not covering all the cases and some of them are old, they are related to the source of this fork
More accurate test for the ng-add feature
The test coverage the 100% of the ng-add file
=> test: refactor the test of the ng-add

CHANGELOG.md
We have a changelog but not in the root of the source code, some bots that create automated dependency updates like [Dependabot](https://dependabot.com/) reads the changlelog of the root.
Create a symbolic link of the changelog in the root of the project to see if those bots are able to put the new features and fixes in their pull request.
The symbolic link is made because the changelog is generated outside the root of the project and this is a quick fix for that problem.
=> docs: set changelog on project root

src/.github/pull_request_template.md
Add the PR template that the Angular team is using
=> chore: add github template

README.md, src/ng-add.spec.ts, src/ng-add.ts
Nx has changed its builder for the publishable libraries and now this package is not being added.
Any builder can be used on the build architect even a custom one.
=> fix: improve library checking

README.md
The `--configuration` section was outdated indicating a wrong default parameter
The `--configuration` documentation now is accurate
=> docs: fix a typo on the documention

README.md
We have an official chat room on the Angular Discord Server
On the readme we have a link to our channel on Angular Discord
=> docs: add discord server

README.md
Fix Discord URL, now it lands directly on the dedicated channel
=> docs: fix discord URL

src/deploy/schema.json, src/engine/engine.spec.ts, src/package.json
Improve the description for a better one
=> docs: improve builder description

README.md, docs/README_contributors.md, src/package.json
Better documentation focused on Contributors
=> docs: improve documentation for contributors

src/collection.json, src/ng-add-schema.json, src/ng-add.spec.ts, src/ng-add.ts, src/package.json
When you are trying to use the ng-add on an Nx project it triggers an error
The ng-add works like a charm on Nx projects.
This fix is needed for #40
FYI @edbzn
=> fix: add options to ngAdd schematic

src/deploy/actions.spec.ts, src/deploy/actions.ts, src/engine/engine.ts, src/package.json
Currently, we only support Angular and React libs
With the change, we can support node and nest libs 
FYI @edbzn
I'm thinking about how to write some documentation to communicate this change, I'll do it in another PR to this feature branch
=> fix: support all nx libraries

docs/README_contributors.md
https://github.com/angular-schule/ngx-deploy-starter/pull/22
by @dianjuar
Lack of instructions on how to debug
Add debugger instructions and general contributors readme improvements
=> docs: add debugging instructions

src/package.json
Just a little tweak on the build command
=> build: create a separate tsconfig file for build

.github/pull_request_template.md, docs/README_contributors.md, src/package.json, tools/create-workspace-angular.sh, tools/create-workspace-nx.sh
It's not fully automated the creation of a workspace
With two commands we can create an Nx and an Angular workspace
=> chore: create scripts to generate workspaces

src/package.json, src/yarn.lock
BREAKING CHANGE: drop version 8 of @angular-devkit
Issue Number: #58 
Update peer dependencies for more accurate ones
Drop version 8 of `@angular-devkit`.
To migrate should update at least to `@angular-devkit` v9
=> chore!: update peer dependencies for more accurate ones

src/deploy/schema.json, src/ng-add-schema.json, src/package.json, src/yarn.lock
Support for AngularV12
Heavily inspired on [Angular Fire](https://github.com/angular/angularfire/pull/2834)
=> feat: support Angular v12

.github/actions/setup/action.yml, .github/workflows/ci.yml
=> build: configure continuous integration

.github/pull_request_template.md, .husky/commit-msg, docs/README_contributors.md, package.json, yarn.lock
No commit validation was implemented, leading to do not logging a feature in the changelog.
Use Semver generator to ensure the commit guidelines implementation
=> chore(workspace): automage the commit message creation

.github/workflows/nightly-version-health.yml
Create checks on the CI to verify test, build, and e2e test on master branch
=> ci: create checks for nightly version

README.md
Continuation of #96  
Put on the readme a badge to indicate the health check on the nightly version.
=> docs: put a badge to indicate the health of the nightly version

.github/workflows/ci.yml
Change the name to analyze PR's workflow
=> ci: change continuous integration workflow name to PR's

.github/actions/setup/action.yml, .github/workflows/ci.yml
Improve the set of test made on the CI for PR's
=> ci: improve ci test

.github/workflows/basic-test.yml
=> ci: change workflow name

.github/actions/download-build/action.yml, .github/workflows/basic-test.yml, .github/workflows/nightly-version-health.yml, .github/workflows/publishment.yml, docs/README_contributors.md, packages/ngx-deploy-npm/project.json
Integrate continuous deployment
=> ci: change workflow name (#101)

.github/workflows/basic-test.yml, packages/ngx-deploy-npm/project.json
When generating the version, the package is not being built again to generate the new version and tries to publish the previous one.
After the version is bumped, the build is handled by ngx-deploy-bpm to put the new version on the `package.json` and then publish it to NPM.
=> ci: simulate publishment on PR

.github/workflows/publishment.yml
Generates a tag on each release
=> ci: generate last release tag on each deployment

package.json, yarn.lock
=> chore: update nx deps

renovate.json
Auto merge wasn't working
A better configuration for renovate that seems to fix the automerge
=> chore: improve renovate automerge config

README.md, docs/README_contributors.md
=> docs: improve documentation (grammatical)

renovate.json
Renovate bot is too noisy
Create the PRs only on early mondays
=> chore: set schedule on renovate

.github/workflows/publishment.yml, packages/ngx-deploy-npm/project.json
Create a pre-publishment step previous to the real publishment; there we can see which would be the next version and the changelog generated. This change will help to catch errors and check if everything looks alright before the real publish
=> ci: improve publishment workflow

.github/workflows/publishment.yml
We have master protected and it's failing to push the generated changelog and tags on publishing
Use a new action to allows us to push to protected branches
=> ci: fix pushed to protected branches

.github/pull_request_template.md, .github/workflows/ci.yml
On the PR workflow, add commit lint check
=> ci: add commit check on ci

.github/workflows/publishment.yml
Add sonarque analysis on master
=> ci: add Sonarqube Analysis on main branch

.github/workflows/publishment.yml
Sonar Analysis is failing on the main branch.
https://github.com/bikecoders/ngx-deploy-npm/runs/4158280471?check_suite_focus=true
Apply the suggested fix on the logs
=> ci: fix main sonar analysis

README.md
=> docs: add sonar badges on readme

.github/actions/setup/action.yml
Improve the action setup to handle the node_modules cache
The node cache on the CI seems not to be working. It takes a considerable amount of time each time it needs to do `yarn install`
Read the documentation of the action used to install dependencies and implement their cache system.
An analysis was made to measure which impact has this new configuration. The results were positive, **an improvement of 🟢 31%** on average, including jobs with multiple node versions.
| Action               | [Time1][newt1] | [Time2][newt2] | [Time3][newt2] |  Avg  |
| :------------------- | -------------: | -------------: | -------------: | :---: |
| lint                 |             21 |             21 |             21 |  21 …
=> ci: improve CI operations time by 32% in average

renovate.json
Issue Number: #161
- Remove auto-merge strategy. It isn't working.
- Change semantic commit prefix
- `@nrwl` packages are updated every day
- The rest of the dependencies are updated every month
=> build: improve renovate frequency

.github/workflows/publishment.yml
Update the action `CasperWA/push-protected` to the latest version. Update the parameter `branch` to `ref`, to obtain the branch automatically
=> ci: update push to protected step

.github/workflows/publishment.yml, packages/ngx-deploy-npm/project.json
Simplify targets on `workspace.json`
=> ci: clean up project.json

README.md
Issue Number: #89 
Add [`@jscutlery/semver`](https://github.com/jscutlery/semver) on our documentation to suggest the users to use that package to generate their package versions
FYI @edbzn
=> docs: add semver to the documentation

docker-compose.yml, docs/README_contributors.md, package.json, tools/docker/sonarqube/change_password.sh, tools/docker/sonarqube/env_vars
Issue Number: #192 
Run `npm run sonar:init-server` to init sonarqube server and to run the analysis run `npm run sonar:analysis`
=> build: dockerize sonarqube for local development

.github/actions/download-build/action.yml, .github/actions/download-coverage-report/action.yml, .github/workflows/basic-test.yml, .github/workflows/ci.yml, .github/workflows/publishment.yml, packages/ngx-deploy-npm/jest.config.js, sonar-project.properties
The sonar analysis now analyses the code coverage of all new code introduced
=> build: fix sonarqube coverage

sonar-project.properties
The coverage path finding is failing on master
Set as relative path the coverage report path to check if that fixes the analysis on master
=> build: set as relative path the coverage report path

.github/workflows/ci.yml, .husky/pre-commit, package.json, yarn.lock
Issue Number: #193 
- Prettier executed for staged files
- Run a CI check to verify if the developer ran prettier
=> ci: improve prettier usage

docker-compose.yml, sonar-project.properties, tools/docker/sonarqube/change_password.sh
The coverage report is working properly on PR analysis but not on the main analysis
Provide absolute paths instead of relative on coverage report
=> build: provide absolute path on sonarqube coverage report

.github/workflows/publishment.yml
On the main analysis, the coverage report was not being loaded
Load the coverage report on the main analysis
=> ci: fix sonarqube coverage report on main analysis

README.md, e2e/ngx-deploy-npm-e2e/tests/install.test-factory.ts, e2e/ngx-deploy-npm-e2e/tests/ngx-deploy-npm.spec.ts, e2e/ngx-deploy-npm-e2e/tests/utils/utils-ngx-deploy-npm.ts, packages/ngx-deploy-npm/src/generators/install/generator.spec.ts, packages/ngx-deploy-npm/src/generators/install/generator.ts, packages/ngx-deploy-npm/src/generators/install/schema.d.ts, packages/ngx-deploy-npm/src/generators/install/schema.json, packages/ngx-deploy-npm/src/generators/install/utils/index.ts, packages/ngx-deploy-npm/src/generators/install/utils/validate-projects.ts
Issue Number: #71
`--projects` option created in init generator to specify which libraries should be configured.
=> feat: create --projects option on install

.github/actions/download-lint-report/action.yml, .github/workflows/basic-test.yml, .github/workflows/ci.yml, .github/workflows/publishment.yml, .gitignore, package.json, packages/ngx-deploy-npm/project.json, packages/ngx-deploy-npm/src/generators/init/generator.ts, sonar-project.properties, tools/sonarqube-linter-reporter.js, yarn.lock
Issue Number: #202 
Create a new lint reporter to generate reports compatible with what sonarqube needs and modify the CI to generate those lint reports
A linter error was introduced on purpose to check if the report is generated correctly
=> ci: add lint report to sonarqube analysis

.github/workflows/ci.yml, packages/ngx-deploy-npm/src/generators/init/generator.ts
Issue Number:  N/A
A linter error was put on purpose to test linter report on sonarqube
Remove the linter error
This is related to #202
=> ci: remove lint error put on purpose to test lint reports

.github/workflows/ci.yml, package.json, renovate.json, tools/create-angular-workspace.sh, yarn.lock
Issue Number: #158 
Create simple angular e2e using a bash script and run it on the CI.
By the moment they are only on the PR analysis not on the main workflow, I want to wait a little bit and see how it behaves.
=> ci: create simple angular e2e test

README.md
=> fix(docs): property 'dryRun' does not match the schema. 'true' should be a 'boolean'.

.github/FUNDING.yml, .vscode/settings.json, .vscode/tasks.json, README.md, docs/README_contributors.md
=> style: execute nx format globally

.github/workflows/publishment.yml
=> ci: remove e2e dependency from release-preliminar

e2e/ngx-deploy-npm-e2e/tests/deploy/libs/nx-plugin.test-factory.ts, e2e/ngx-deploy-npm-e2e/tests/utils/get-nrwl-current-version.ts, e2e/ngx-deploy-npm-e2e/tests/utils/index.ts, e2e/ngx-deploy-npm-e2e/tests/utils/install-deps.ts, e2e/ngx-deploy-npm-e2e/tsconfig.spec.json
=> test(e2e): use same nrwl version present on package.json on e2e test

renovate.json
The commit message is not working as expected on lock maintenance PRs
=> fix: renovate commit message prefix

renovate.json
The commit message is not working as expected on lock maintenance PRs
=> build: renovate commit message prefix on lock maintenance PR

README.md
Missing Node.js supported versions
Issue Number: (#302)
Node.js supported versions badge in `README.md`
=> feat: update README.md add node supported versions badge (#302)

README.md, e2e/ngx-deploy-npm-e2e/tests/install.test-factory.ts, packages/ngx-deploy-npm/src/executors/deploy/schema.d.ts, packages/ngx-deploy-npm/src/executors/deploy/schema.json, packages/ngx-deploy-npm/src/generators/install/generator.spec.ts, packages/ngx-deploy-npm/src/generators/install/generator.ts, packages/ngx-deploy-npm/src/generators/install/schema.d.ts, packages/ngx-deploy-npm/src/generators/install/schema.json, packages/ngx-deploy-npm/src/generators/install/utils/normalize-options.ts
Issue Number: close #206
Add the option `access` to ng-add/install to indicate the scope of the package; it could be `public`
or `restricted`
=> feat: add `access` option to ng-add/install

.github/workflows/publishment.yml, README.md, docs/README_contributors.md, nx.json, renovate.json
Update branch `master` for `main`
=> ci: rename master to main

.github/workflows/angular-e2e-test.yml, .github/workflows/basic-test.yml, .github/workflows/ci.yml, .github/workflows/e2e-test.yml, .github/workflows/next-test.yml
Issue Number: #299 
Perform 4 times a day unit and E2E tests against `@next` version of the packages `@nrwl` and `@angular`
=> ci: create workflow to perform test against @next version

.github/workflows/next-test.yml, README.md
Issue Number: #299 
Add badge on readme to indicate pipeline tests status
=> docs: add next tests pipeline badge to readme

.github/workflows/angular-e2e-test.yml, tools/create-angular-workspace.sh
Run Angular E2E Tests with different node versions
=> ci: run angular e2e tests with different node versions

packages/ngx-deploy-npm/src/executors/deploy/schema.d.ts, packages/ngx-deploy-npm/src/executors/deploy/schema.json
=> fix: allow otp to be a number

.github/workflows/publishment.yml
=> ci: run angular tests on publishment

README.md
Issue Number: #392
Remove the section from the readme
=> Remove readme and license from special consideration

README.md
=> docs: fix markdown style on main documentation

packages/ngx-deploy-npm/project.json
The images used on the readme are not being copied on the bundle
Copy all the images used on the readme into the dist bundle
=> docs: copy all readme images into the bundle

.github/actions/setup/action.yml, .github/workflows/basic-test.yml, .github/workflows/e2e-test.yml, README.md, packages/ngx-deploy-npm/src/__mocks__/child_process/index.ts, packages/ngx-deploy-npm/src/__mocks__/generators/index.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/dist-folder-path/dist-folder-path-option.spec.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/dist-folder-path/dist-folder-path-option.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/ng-package/ng-package.spec.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/ng-package/ng-package.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/output-path-build-option/output-path-build-option.spec.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/output-path-build-option/output-path-build-option.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/spawn-async.spec.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/spawn-async.ts
Issue Number: #418
We consider windows os when executing the command `npm publish`.
Also, we now run E2E test on windows os (#417)
=> fix: fix command execution on windows os

packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/dist-folder-path/dist-folder-path-option.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/ng-package/ng-package.ts, packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategies/output-path-build-option/output-path-build-option.ts
There was a lack of documentation about the process of locating the dist folder path
A header comment was added to each strategy to document each one of them
=> docs: document the strategies to locate the dist folder path

packages/ngx-deploy-npm/src/executors/deploy/utils/get-lib-output-path/strategy-selector.ts
Fix a grammar error on error `NotAbleToDetermineDistPathError`
=> fix: fix grammar on "not able to determine dist folder path" error mesage

packages/ngx-deploy-npm/package.json
Currently there is no support for nx@14
fix #469
nx@14 and @15 supported 👍 
Both nx 14 and 15 were manually tested, and everything worked as expected.
CC @samuelfernandez @dgonzalezr
=> feat: offer support to nx@14

e2e/ngx-deploy-npm-e2e/integration/react-native.spec.ts
React Native integration tests are broken.
Install the right dependencies versions
=> test: fix react-native integration test

migrations.json, nx.json, package-lock.json, package.json, packages/ngx-deploy-npm/project.json
This fixes the e2e tests that are currently failing. No misfunction was detected when running the automation test (`npx nx create-nx-workspace ngx-deploy-npm`), so that suggests the e2e tests are failing due to some misconfiguration on the Nx workspace.
=> build: update nx

packages/ngx-deploy-npm/package.json
Update ngx-deploy-npm package.json to match the current node version support
=> build: update package's package.json node version to 18

package-lock.json
=> build: refresh package-lock

.github/workflows/test-nx-next.yml
=> ci: fix next linter workflow

.github/workflows/publishment.yml, packages/ngx-deploy-npm/project.json
Issue Number: #244 
Implement `@jscutlery/semver:github` to automate github releases
=> ci: implement github releases on deployment

.github/workflows/integration-test-nx-workspace.yml, .github/workflows/publishment.yml, packages/ngx-deploy-npm/project.json
Use semver options to push first just created version
=> ci: fix github releases

packages/ngx-deploy-npm/project.json
GitHub releases are preventing us from creating a new release.
We are rolling back the GitHub releases to continue delivering features and to address the problem later in a more thoughtful phase.
=> ci: remove github releases

packages/ngx-deploy-npm/project.json
=> ci: remove semver config to push on github

.github/workflows/publishment.yml
=> ci: remove github secret from version and publishment step

package-lock.json, package.json
=> build: update nx to 19.2.3

nx.json, package-lock.json
feat(nx-cloud): setup nx cloud workspace 
This commit set up Nx Cloud for your Nx workspace enabling distributed caching
and GitHub integration for fast CI and improved Developer Experience.
You can access your Nx Cloud workspace by going to 
https://cloud.nx.app/orgs/66687a051fafcb200530b4ca/workspaces/66687a17435d193ea382fed5
**Note:** This commit attempts to maintain formatting of the nx.json, however you may need to correct formatting by running an nx format command and committing the changes.
=> ci(nx-cloud): setup nx workspace

package-lock.json, package.json
Issue Number: close #607
Update latest version of semver to support Nx19
=> build: update semver

.github/workflows/publishment.yml
Currently, the changes made by the CI are not being pushed to the repo, requiring manual action to finish a deployment properly.
Fix the push of changes made by the CI
=> ci: fix publishment workflow

nx.json, package-lock.json
=> build: update nx to 20.0.3

nx.json
=> chore: remove deprecated nx.json option

.github/workflows/compatibility-observability.yml
=> ci: fix compatibility observability test

.github/workflows/backwards-compatibility-test.yml, .github/workflows/smoke-test-nx-workspace.yml, packages/ngx-deploy-npm-e2e/src/utils/basic-setup.ts
Create verbose mode for smoke test and run in verbose mode the retro compatibility tests to verify the right execution of them
=> ci: create verbose mode for smoke test

packages/ngx-deploy-npm/package.json
We currently provide support for nx@16.10.0, which is compatible with node v16. This commit updates the minimum node version required for this package to reflect that compatibility.
=> fix: update the node version to 16 on package.json

.github/workflows/sonar-pr.yml
=> ci: fix SonarQube PR workflow

.github/actions/download-build/action.yml, .github/actions/download-coverage-report/action.yml, .github/actions/download-lint-report/action.yml, .github/workflows/pr.yml
=> ci: fix download coverage for sonar workflow

.github/actions/download-build/action.yml, .github/actions/download-coverage-report/action.yml, .github/actions/download-lint-report/action.yml, .github/workflows/pr.yml, .github/workflows/sonar-pr.yml
=> ci: try another technique to download reports on sonar workflow

.github/workflows/sonar-pr.yml
=> ci: adding debug info to sonar pr workflow

.github/workflows/sonar-pr.yml
=> ci: fix sonar qube token name

.github/workflows/basic-test.yml, .github/workflows/pr.yml
=> ci: restore all test in continuous integration flow

.github/workflows/publishment.yml, .github/workflows/sonar-pr.yml
The Github Action used for sonarqube analysis was deprecated. It peplaces it with a drop-in replacement.
=> ci: migrate sonar cloud scanner action

.github/workflows/pr.yml
=> ci: fix sonar action name

.github/workflows/sonar-pr.yml
=> ci: fix sonarqube action version

.github/workflows/publishment.yml
=> ci: update gh action for sonar scanner main analysis
