bikecoders/ngx-deploy-npm

src/deploy/actions.spec.ts
src/deploy/actions.ts
src/package-lock.json

The seeder used force to have the configuration `production` when building the app. We do not need to do it on libraries.
close #2

fix: do not force to build on production

---

README.md
src/ng-add.spec.ts
src/ng-add.ts

Right now, on `ng add ngx-deploy-npm` the deployer is set on all libraries even on those that are not publishable. 
On [nx](https://nx.dev) you can have publishable an non-publishable libraries (internal libraries) and adding the deployer to non-publishable libraries is pointless.
Issue Number: The is an issue on NX related to this feature ([nx 1800](https://github.com/nrwl/nx/issues/1800))
Only set the deployer on publishable libraries adding [nx](https://nx.dev) compatibility.

feat: set deployer only on publishable libraries

---

src/package.json

In the latest versions of the CLI `ng-add` packages can be added to `devDependencies` and this package is perfect for such use case since it's only needed for development.
See: https://github.com/angular/angular-cli/pull/15815

fix: save package in devDependencies

---

src/deploy/schema.json
src/engine/engine.ts
src/engine/utils/fs-async.ts

add an option called `packageVersion` to enable update the package version before publishing to npm

feat: add a packageVersion to options

---

src/deploy/actions.spec.ts
src/deploy/actions.ts

Issue Number: #16 
A cherry-pick was done to implement the fix on this project.
cherry-pick from e7f6a51392dd97973c98b5420c4903d2bc1e2721 of angular-cli-ghpages/master by @masaxsuzu
see https://github.com/angular-schule/angular-cli-ghpages/pull/85

fix: throws an error if app building fails

---

CHANGELOG.md
src/README.md
src/package.json

The symbolic links are kind of difficult to understand
Also, if we have the changelog on a different path, the renovate bots here on GitHub are not able to get the changelog and put it on the PR to upgrade the version, making it difficult for the maintainers, get the latest changes on that scenario is not straight forward.
Removed all the symbolic links and use the original files.

chore: delete symbolic links to README and CHANGELOG files

---

README.md
src/LICENSE
src/deploy/actions.spec.ts
src/deploy/actions.ts
src/deploy/builder.ts
src/deploy/schema.json
src/ng-add.spec.ts
src/ng-add.ts

The parameter configuration is migrated to buildTarget.
For migration just change `--configuration` for `--build-target` on the command line and on the configuration file `configuration` for `buildTarget`

fix!: change configuration parameter for buildTarget

---

packages/ngx-deploy-npm/src/executors/deploy/engine/engine.spec.ts
packages/ngx-deploy-npm/src/executors/deploy/engine/engine.ts

Target-paths with spaces result in an error, because the npm command recieves the path as two inputs
Target-paths can have spaces now

fix: allow paths with spaces

---

package.json
yarn.lock

The Semver's `postTarget` feature did not run the executor with the suitable options; for some reason, all options with default values had as value `true`. For our scenario, `dryRun` and `noBuild` were true, leading to unwanted behavior.
Updating Semver to the last version solve this problem

build(fix): update semver to trigger postTargets feature

---

.github/workflows/publishment.yml

The publishment workflow is executed on undesired commits
Avoid running publishment workflow on autogenerated commits when generating a new version

ci: avoid running publishment deployment on autogenerated commits

---

.github/workflows/basic-test.yml
.github/workflows/ci.yml
.github/workflows/e2e-test.yml
.github/workflows/publishment.yml

Currently, the e2e tests are part of the basic test, and some operations depend on those basic tests to execute. E2E tests take almost 7minutes to complete, and they're slowing down the development process.
E2E we depend on build, lint (coming soon), and unit test to execute other operations but not for e2e test, and there is no way to indicate in a reusable workflow to specify that you need an inner job. https://github.com/github/feedback/discussions/11072
Separate the e2e tests from the primary tests gaining agility and making the CI faster.
Tested on https://github.com/bikecoders/ngx-deploy-npm/actions/runs/1803099858

ci: separate e2e from basic-test

---

.github/workflows/ci.yml
.github/workflows/publishment.yml

We were using a reusable workflow using a repo path. That's inconvenient at the moment of modifying it, you need to toggle the master branch between the branch that you are working and that is error-prone.
Seems that now is possible to reference a reusable workflow using a relative path
https://docs.github.com/en/actions/using-workflows/reusing-workflows#calling-a-reusable-workflow

ci: use reusable workflow using local path instead of repo reference

---

renovate.json

The Dependency Dashboard (#110) is complaining about some warnings in the renovate configuration.
The renovate's log shows the following warning.
[Cypress's](https://github.com/cypress-io/cypress/pull/16396) have faced this issue before

build: remove deprecated option on renovate config

---

renovate.json

The lock file maintenance commit is not showing the package emoji.
Adds the package emoji to the commit message to have a homogeneous renovate's commit messages

build: add package emoji to lock maintenance renovate commit's message

---

.github/workflows/basic-test.yml
.github/workflows/e2e-test.yml

Drop support for node v12 and adopt node v18.
Issue Number: #249
`ngx-deploy-npm` no longer supports node v12. Please update node v14, v16, or v18 to continue support.

build: drop node12 and adopt node18

---

e2e/ngx-deploy-npm-e2e/jest.config.js
packages/ngx-deploy-npm/jest.config.js

> Define ts-jest config under globals is now deprecated. Please define the config via transformer config instead.
See https://github.com/bikecoders/ngx-deploy-npm/pull/377 for `ts-jest` deprecation notes
When running the test, it lunches a warning:
```
ts-jest[ts-jest-transformer] (WARN) Define `ts-jest` config under `globals` is deprecated. Please do
transform: {
<transform_regex>: ['ts-jest', { /* ts-jest config goes here in Jest */ }],
},
```
https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3201478983/jobs/5229501587#step:5:12
Updates ts-jest configuration to v29
Warning gone:
https://github.com/bikecoders/ngx-deploy-npm/actions/runs/3202447548/jobs/5231438195

test: update ts-jest config deprecated on V29

---

packages/ngx-deploy-npm/src/executors/deploy/engine/engine.spec.ts
packages/ngx-deploy-npm/src/executors/deploy/engine/engine.ts

Issue Number: Hotfix for #401
Increment temporary the exec buffer size to prevent errors when executing npm publish for packages with many files.
This is a temporary solution as we migrate from `child_process.exec` [`child_process.spawn`](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) instead.

fix: increment exec buffer size to allow package publishment with a large set of files

---

packages/ngx-deploy-npm/package.json

Applications can't install latest versions of `nx` because the dependency is pinned.
Closes #470 
The dependency version is widened, so any version within last major version of nx `^15.0.0` would be supported.
Potentially this is a breaking change if: 1) Consumer apps doesn't have `nx` installed (Angular workspace) and 2) Using legacy peer dependencies (those won't be installed)
The result would be that installation would fail. Installing peer dependencies is the default since npm 7, so it is been a while already, and as mentioned in #470 it is the standard. If we want to make this change 100% non-breaking, we could keep them as just `dependencies`, and schedule this change for the next major version. Open for comments. …

fix: widen peer dependencies on nx

---

README.md
packages/ngx-deploy-npm/src/executors/deploy/engine/engine.spec.ts
packages/ngx-deploy-npm/src/executors/deploy/engine/engine.ts
packages/ngx-deploy-npm/src/executors/deploy/schema.d.ts
packages/ngx-deploy-npm/src/executors/deploy/schema.json
packages/ngx-deploy-npm/src/executors/deploy/utils/default-options.ts
packages/ngx-deploy-npm/src/executors/deploy/utils/interfaces.ts

Right now there's no ability to deploy to other registries. This might be useful if we want to add another deployment configuration for testing purposes
Adding the new `--registry` options for the deploy executor. This will allow to deploy the package into other registries or tools like https://verdaccio.org/docs/what-is-verdaccio/

feat: add "registry" option for the deploy executor

---

packages/ngx-deploy-npm/project.json
tools/create-nx-workspace.sh

In the past, we had a script to create an nx workspace sandbox to have an actual test workspace. That script was hidden, and its execution was primitive. You had to do it by hand `./tools/create-nx-workspace.sh`
Create a target to create an nx workspace sandbox.
`npx nx create-nx-workspace`
Also, the script now receives a parameter indicating which version creates the nx worspace.
```bash
npx nx create-nx-workspace -- 14.8.6 # will create the nx workspace with nx V14.8.6
```
This could be a potential solution for #482

chore: create nx target to create nx workspace sandbox

---

.eslintrc.json
packages/ngx-deploy-npm/package.json
packages/ngx-deploy-npm/project.json

when installing ngx-deploy-npm 7.0.0 the following error occurs:
```
npm ERR! Found: tslib@2.6.1
npm ERR! node_modules/tslib
npm ERR!   dev tslib@"^2.3.0" from the root project
npm ERR!   tslib@"^2.3.0" from @nx/devkit@16.6.0
npm ERR!   node_modules/@nx/devkit
npm ERR!     peer @nx/devkit@"^16.0.0" from ngx-deploy-npm@7.0.0
npm ERR!     node_modules/ngx-deploy-npm
npm ERR!       dev ngx-deploy-npm@"7.0.0" from the root project
npm ERR!   3 more (nx, @swc-node/register, @swc/helpers)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer tslib@"1.14.1" from ngx-deploy-npm@7.0.0
npm ERR! node_modules/ngx-deploy-npm
npm ERR!   dev ngx-deploy-npm@"7.0.0" from the root project
```
The option …

fix: set the right peerDependency on ngx-deploy-npm's package.json

---

.github/actions/setup/action.yml
.github/workflows/backwards-compatibility-test.yml
.github/workflows/basic-test.yml
.github/workflows/e2e-test.yml
.github/workflows/integration-test-nx-workspace.yml
docs/README_contributors.md

Modify the unit, e2e and regression test to run them against different node versions

ci: run test against different node versions

---

README.md
packages/ngx-deploy-npm-e2e/src/publish.spec.ts
packages/ngx-deploy-npm/src/executors/deploy/engine/engine.spec.ts
packages/ngx-deploy-npm/src/executors/deploy/engine/engine.ts
packages/ngx-deploy-npm/src/executors/deploy/schema.d.ts
packages/ngx-deploy-npm/src/executors/deploy/schema.json

fixes: https://github.com/bikecoders/ngx-deploy-npm/issues/666
fixes: https://github.com/bikecoders/ngx-deploy-npm/issues/508
This commit adds a new optional flag `checkExisting` that allows users to verify if a package version already exists in the registry before publishing. When enabled, it will:
- Check the package.json for name and version
- Query npm registry for existing versions
- Skip publishing if version already exists
- Default to false to maintain backward compatibility and avoid regression
- Add test
- Add documentation
This helps prevent accidental republishing package and having issue (403) when trying to republish a version that is already pushed (on gitlab for example)
Issue Number: …

feat(ngx-deploy-npm): add version check to prevent duplicate publishes

---

.github/workflows/pr.yml
.github/workflows/sonar-pr.yml

Issue Number: #671 
Adding a new workflow `sonar-pr.yml` for SonarCloud analysis on successful PR runs. This new workflow is triggered by `workflow_run`, which allows secrets to be shared with PR's from forked repos.
According to the [documentation for `workflow_run`](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run), the workflow must be on the main branch. This requirement makes it impossible to test the new CI configuration. We need to merge this PR to see the results.

ci: enable sonarqube analysis for contributors

---

.github/workflows/basic-test.yml
.github/workflows/sonar-pr.yml

Issue Number: #671 
Turns out what:
> Yes, `git log -1 --format=%H` should be equal to `github.sha` in the CI runtime if you're running the workflow on the same commit. However, there are a few scenarios where they might not match:
- **Pull Request workflows:** GitHub creates a merge commit by merging your branch with the target branch. In this case:
- Your local: `your-branch-commit`
- GitHub Actions: `temporary-merge-commit`
The new behavior ensures that the commit SHA is consistent across different GitHub Actions workflows. This addresses scenarios in pull request workflows where GitHub creates a temporary merge commit, causing discrepancies between the local branch commit SHA and the one used in the GitHub Actions …

ci: make commit sha consistent across workflows

---

.github/actions/download-build/action.yml
.github/actions/download-coverage-report/action.yml
.github/actions/download-lint-report/action.yml
.github/workflows/basic-test.yml
.github/workflows/compatibility-observability.yml
.github/workflows/sonar-pr.yml

GitHub Actions provides isolated artifact storage for each workflow run. Since artifacts are only shared between jobs within the same workflow run:
1. There's no risk of name collisions between different runs
2. Jobs can only access artifacts from their own workflow run
3. Each run has its own isolated artifact storage space
The SHA suffixes were adding unnecessary complexity without providing any benefits for intra-workflow artifact sharing.

ci: simplify upload and download artifacts

---

.github/actions/download-lint-report/action.yml
.github/workflows/basic-test.yml
.github/workflows/pr.yml
.github/workflows/sonar-pr.yml
packages/ngx-deploy-npm/project.json
sonar-project.properties

Issue Number: #671 
The current SonarQube action being used is deprecated, which may cause issues in CI/CD workflows.
The deprecated SonarQube action has been replaced with a supported and updated action, ensuring compatibility and continued functionality in CI/CD workflows.

ci: replace deprecated sonarqube action

---

.github/workflows/basic-test.yml
.github/workflows/sonar-pr.yml

ci: fix download reports on sonarqube
